package com.farmconnect.automation.tests.crud;

import com.farmconnect.automation.base.BaseTest;
import com.farmconnect.automation.utils.RetryAnalyzer;
import org.testng.Assert;
import org.testng.annotations.*;

/** CrudOperationsTests - 20 test cases for CRUD operations on listings/marketplace. */
public class CrudOperationsTests extends BaseTest {
    @BeforeMethod(alwaysRun = true, dependsOnMethods = "methodSetup")
    public void setup() { loginAsTestUser(); }

    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_001_readListings() { navigateToSection("marketplace"); int count = (int)(long)(Long)executeScript("return JSON.parse(localStorage.getItem('fc_listings')||'[]').length;"); Assert.assertTrue(count >= 0); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_002_createListing() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.push({id:999,crop:'TestCrop',qty:'100kg',price:1000,location:'Test',seller:'Test',phone:'9876543210'});localStorage.setItem('fc_listings',JSON.stringify(l));"); int count = (int)(long)(Long)executeScript("return JSON.parse(localStorage.getItem('fc_listings')).length;"); Assert.assertTrue(count >= 1); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_003_readCreatedListing() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.push({id:998,crop:'ReadCrop',qty:'50kg',price:500,location:'Test',seller:'Test',phone:'9876543210'});localStorage.setItem('fc_listings',JSON.stringify(l));"); Object crop = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).find(l=>l.id===998).crop;"); Assert.assertEquals(crop, "ReadCrop"); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_004_updateListing() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');if(l.length>0){l[0].price=9999;localStorage.setItem('fc_listings',JSON.stringify(l));}"); Object price = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings'));return l.length>0?l[0].price:0;"); Assert.assertEquals(((Number)price).intValue(), 9999); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_005_deleteListing() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');var orig=l.length;l=l.filter(x=>x.id!==999);localStorage.setItem('fc_listings',JSON.stringify(l));"); Assert.assertTrue(true); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_006_listingsPageRenders() { navigateToSection("marketplace"); Assert.assertEquals(getActiveSection(), "marketplace"); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_007_createMultipleListings() { for(int i=0;i<3;i++) executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.push({id:"+(900+i)+",crop:'Crop"+i+"',qty:'10kg',price:100,location:'Test',seller:'Test',phone:'9876543210'});localStorage.setItem('fc_listings',JSON.stringify(l));"); Object count = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).length;"); Assert.assertTrue(((Number)count).intValue() >= 3); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_008_updateListingQuantity() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');if(l.length>0){l[0].qty='999kg';localStorage.setItem('fc_listings',JSON.stringify(l));}"); Object qty = executeScript("return JSON.parse(localStorage.getItem('fc_listings'))[0].qty;"); Assert.assertEquals(qty, "999kg"); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_009_updateListingLocation() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');if(l.length>0){l[0].location='Updated Location';localStorage.setItem('fc_listings',JSON.stringify(l));}"); Object loc = executeScript("return JSON.parse(localStorage.getItem('fc_listings'))[0].location;"); Assert.assertEquals(loc, "Updated Location"); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_010_deleteNonExistentListing() { Object before = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).length;"); executeScript("var l=JSON.parse(localStorage.getItem('fc_listings'));l=l.filter(x=>x.id!==-1);localStorage.setItem('fc_listings',JSON.stringify(l));"); Object after = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).length;"); Assert.assertEquals(before, after); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_011_listingDataIntegrity() { Object data = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings'));return l[0]?typeof l[0].crop==='string':true;"); Assert.assertEquals(data, true); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_012_emptyListingsArray() { executeScript("localStorage.setItem('fc_listings','[]');"); Object count = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).length;"); Assert.assertEquals(((Number)count).intValue(), 0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_013_listingsIDUniqueness() { Object unique = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');var ids=l.map(x=>x.id);return new Set(ids).size===ids.length;"); Assert.assertEquals(unique, true); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_014_createListingWithAllFields() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.push({id:997,crop:'FullCrop',qty:'200kg',price:3000,location:'Full Location',seller:'Full Seller',phone:'9999999999',status:'active'});localStorage.setItem('fc_listings',JSON.stringify(l));"); Object crop = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).find(x=>x.id===997).crop;"); Assert.assertEquals(crop, "FullCrop"); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_015_bulkDelete() { executeScript("localStorage.setItem('fc_listings','[]');"); Object count = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).length;"); Assert.assertEquals(((Number)count).intValue(), 0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_016_listingsSurviveRefresh() { executeScript("location.reload();"); try{Thread.sleep(3000);}catch(Exception e){} Object listings = executeScript("return localStorage.getItem('fc_listings');"); Assert.assertNotNull(listings); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_017_updatePreservesOtherFields() { executeScript("var l=[{id:1,crop:'Test',qty:'10',price:100,location:'L',seller:'S',phone:'9876543210'}];localStorage.setItem('fc_listings',JSON.stringify(l));"); executeScript("var l=JSON.parse(localStorage.getItem('fc_listings'));l[0].price=200;localStorage.setItem('fc_listings',JSON.stringify(l));"); Object crop = executeScript("return JSON.parse(localStorage.getItem('fc_listings'))[0].crop;"); Assert.assertEquals(crop, "Test"); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_018_ordersStorageExists() { Object orders = executeScript("return localStorage.getItem('fc_orders');"); Assert.assertTrue(orders == null || orders != null, "Orders storage should be accessible"); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_019_createOrder() { executeScript("var o=JSON.parse(localStorage.getItem('fc_orders')||'[]');o.push({id:1,crop:'Wheat',qty:'100',status:'active'});localStorage.setItem('fc_orders',JSON.stringify(o));"); Object count = executeScript("return JSON.parse(localStorage.getItem('fc_orders')).length;"); Assert.assertEquals(((Number)count).intValue(), 1); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_020_updateOrderStatus() { executeScript("var o=[{id:1,status:'active'}];localStorage.setItem('fc_orders',JSON.stringify(o));"); executeScript("var o=JSON.parse(localStorage.getItem('fc_orders'));o[0].status='completed';localStorage.setItem('fc_orders',JSON.stringify(o));"); Object status = executeScript("return JSON.parse(localStorage.getItem('fc_orders'))[0].status;"); Assert.assertEquals(status, "completed"); }
}
