package com.farmconnect.automation.tests.crud;
import com.farmconnect.automation.base.BaseTest;
import com.farmconnect.automation.utils.RetryAnalyzer;
import org.testng.Assert;
import org.testng.annotations.*;

/** CrudAdvancedTests - 20 more CRUD test cases. */
public class CrudAdvancedTests extends BaseTest {
    @BeforeMethod(alwaysRun = true, dependsOnMethods = "methodSetup") public void setup() { loginAsTestUser(); }

    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_021_readAllUsers() { Object count = executeScript("return JSON.parse(localStorage.getItem('fc_users')||'[]').length;"); Assert.assertTrue(((Number)count).intValue()>=1); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_022_createUserDirectly() { executeScript("var u=JSON.parse(localStorage.getItem('fc_users')||'[]');u.push({name:'Direct',phone:'9999999991',password:'p',role:'farmer',location:'L'});localStorage.setItem('fc_users',JSON.stringify(u));"); Assert.assertTrue(true); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_023_deleteUser() { executeScript("var u=JSON.parse(localStorage.getItem('fc_users')||'[]');u=u.filter(x=>x.phone!=='9999999991');localStorage.setItem('fc_users',JSON.stringify(u));"); Assert.assertTrue(true); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_024_updateUserPassword() { executeScript("var u=JSON.parse(localStorage.getItem('fc_users')||'[]');if(u.length>0){u[0].password='newpass';localStorage.setItem('fc_users',JSON.stringify(u));}"); Assert.assertTrue(true); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_025_listingsSortByPrice() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.sort((a,b)=>a.price-b.price);localStorage.setItem('fc_listings',JSON.stringify(l));"); Assert.assertTrue(true); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_026_listingsFilterByCrop() { Object count = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop==='wheat'||x.crop==='Wheat').length;"); Assert.assertTrue(((Number)count).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_027_listingsFilterByLocation() { Object count = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.location&&x.location.includes('Delhi')).length;"); Assert.assertTrue(((Number)count).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_028_batchCreateListings() { executeScript("var l=[];for(var i=0;i<10;i++)l.push({id:800+i,crop:'Batch'+i,qty:'1kg',price:i*10,location:'L',seller:'S',phone:'9876543210'});localStorage.setItem('fc_listings',JSON.stringify(l));"); Object c = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).length;"); Assert.assertEquals(((Number)c).intValue(),10); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_029_listingsMaxSize() { Object size = executeScript("return localStorage.getItem('fc_listings').length;"); Assert.assertTrue(((Number)size).intValue()>0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_030_clearAllListings() { executeScript("localStorage.setItem('fc_listings','[]');"); Object c = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).length;"); Assert.assertEquals(((Number)c).intValue(),0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_031_listingValidJSON() { Object valid = executeScript("try{JSON.parse(localStorage.getItem('fc_listings'));return true;}catch(e){return false;}"); Assert.assertEquals(valid,true); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_032_usersValidJSON() { Object valid = executeScript("try{JSON.parse(localStorage.getItem('fc_users'));return true;}catch(e){return false;}"); Assert.assertEquals(valid,true); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_033_createListingNegPrice() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.push({id:996,crop:'Neg',qty:'1',price:-100,location:'L',seller:'S',phone:'9876543210'});localStorage.setItem('fc_listings',JSON.stringify(l));"); Object price = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).find(x=>x.id===996).price;"); Assert.assertEquals(((Number)price).intValue(),-100); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_034_createListingZeroPrice() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.push({id:995,crop:'Zero',qty:'1',price:0,location:'L',seller:'S',phone:'9876543210'});localStorage.setItem('fc_listings',JSON.stringify(l));"); Assert.assertTrue(true); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_035_updateNonExistent() { executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');var idx=l.findIndex(x=>x.id===-999);"); Assert.assertTrue(true, "Should handle gracefully"); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_036_listingFieldTypes() { executeScript("var l=[{id:1,crop:'Test',qty:'10',price:100}];localStorage.setItem('fc_listings',JSON.stringify(l));"); Object type = executeScript("return typeof JSON.parse(localStorage.getItem('fc_listings'))[0].price;"); Assert.assertEquals(type,"number"); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_037_concurrentUpdates() { for(int i=0;i<5;i++) executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');if(l.length>0)l[0].price="+(100+i)+";localStorage.setItem('fc_listings',JSON.stringify(l));"); Assert.assertTrue(true); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_038_orderCreateDelete() { executeScript("localStorage.setItem('fc_orders',JSON.stringify([{id:1}]));"); executeScript("localStorage.setItem('fc_orders','[]');"); Object c = executeScript("return JSON.parse(localStorage.getItem('fc_orders')).length;"); Assert.assertEquals(((Number)c).intValue(),0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_039_listingsReloadSafe() { executeScript("var l=[{id:1,crop:'Safe'}];localStorage.setItem('fc_listings',JSON.stringify(l));location.reload();"); try{Thread.sleep(3000);}catch(Exception e){} Assert.assertTrue(true); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_CRUD_040_storagePersistence() { Object keys = executeScript("return Object.keys(localStorage).length;"); Assert.assertTrue(((Number)keys).intValue()>=1); }
}
