package com.farmconnect.automation.tests.validation;
import com.farmconnect.automation.base.BaseTest;
import com.farmconnect.automation.data.TestData;
import com.farmconnect.automation.utils.RetryAnalyzer;
import org.testng.Assert;
import org.testng.annotations.*;

/** InputValidationTests - 20 test cases for input validation. */
public class InputValidationTests extends BaseTest {
    @BeforeMethod(alwaysRun = true, dependsOnMethods = "methodSetup") public void setup() { clearAppState(); }

    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_001_emptyPhoneRejected() { performLogin("","pass"); Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_002_shortPhoneRejected() { performLogin("12345","pass"); Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_003_alphaPhoneRejected() { performLogin("abcdefghij","pass"); Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_004_specialCharsPhoneRejected() { performLogin("!@#$%^&*()","pass"); Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_005_emptyPasswordRejected() { performLogin("9876543210",""); Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_006_phoneMaxLengthEnforced() { Object ml = executeScript("return document.getElementById('loginPhone').maxLength;"); Assert.assertEquals(((Number)ml).intValue(),10); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_007_regNameEmptyRejected() { clickElement("#showRegister"); try{Thread.sleep(500);}catch(Exception e){} executeScript("document.getElementById('regName').value='';document.getElementById('regPhone').value='9444444444';document.getElementById('regPassword').value='pass1234';document.getElementById('regLocation').value='Delhi';document.getElementById('registerBtn').click();"); try{Thread.sleep(1000);}catch(Exception e){} Assert.assertTrue(isElementVisible("#regError") || isAuthScreenDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_008_regNameTooShort() { clickElement("#showRegister"); try{Thread.sleep(500);}catch(Exception e){} executeScript("document.getElementById('regName').value='AB';document.getElementById('regPhone').value='9444444445';document.getElementById('regPassword').value='pass1234';document.getElementById('regLocation').value='Delhi';document.getElementById('registerBtn').click();"); try{Thread.sleep(1000);}catch(Exception e){} Assert.assertTrue(isElementVisible("#regError") || isAuthScreenDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_009_regNameWithNumbers() { clickElement("#showRegister"); try{Thread.sleep(500);}catch(Exception e){} executeScript("document.getElementById('regName').value='Name123';document.getElementById('regPhone').value='9444444446';document.getElementById('regPassword').value='pass1234';document.getElementById('regLocation').value='Delhi';document.getElementById('registerBtn').click();"); try{Thread.sleep(1000);}catch(Exception e){} Assert.assertTrue(isElementVisible("#regError") || isAuthScreenDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_010_regPhoneStartsWithLow() { clickElement("#showRegister"); try{Thread.sleep(500);}catch(Exception e){} executeScript("document.getElementById('regName').value='Valid Name';document.getElementById('regPhone').value='1234567890';document.getElementById('regPassword').value='pass1234';document.getElementById('regLocation').value='Delhi';document.getElementById('registerBtn').click();"); try{Thread.sleep(1000);}catch(Exception e){} Assert.assertTrue(isElementVisible("#regError") || isAuthScreenDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_011_regPasswordTooShort() { clickElement("#showRegister"); try{Thread.sleep(500);}catch(Exception e){} executeScript("document.getElementById('regName').value='Valid Name';document.getElementById('regPhone').value='9444444447';document.getElementById('regPassword').value='ab';document.getElementById('regLocation').value='Delhi';document.getElementById('registerBtn').click();"); try{Thread.sleep(1000);}catch(Exception e){} Assert.assertTrue(isElementVisible("#regError") || isAuthScreenDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_012_sqlInjectionInName() { clickElement("#showRegister"); try{Thread.sleep(500);}catch(Exception e){} executeScript("document.getElementById('regName').value=\"'; DROP TABLE--\";document.getElementById('regPhone').value='9444444448';document.getElementById('regPassword').value='pass1234';document.getElementById('regLocation').value='Delhi';document.getElementById('registerBtn').click();"); try{Thread.sleep(1000);}catch(Exception e){} Assert.assertTrue(isAuthScreenDisplayed(), "Should not crash on SQL injection"); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_013_xssInName() { Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_014_unicodeInName() { Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_015_emojiInName() { Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_016_whitespaceOnlyPhone() { performLogin("          ","pass"); Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_017_phoneWithDashes() { performLogin("987-654-321","pass"); Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_018_phoneWithCountryCode() { performLogin("+919876543210","pass"); Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_019_longStringInput() { performLogin("a".repeat(1000),"pass"); Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_IVAL_020_nullCharacters() { performLogin("9876\0543210","pass"); Assert.assertTrue(isAuthScreenDisplayed()); }
}
