package com.farmconnect.automation.tests.search;
import com.farmconnect.automation.base.BaseTest;
import com.farmconnect.automation.utils.RetryAnalyzer;
import org.testng.Assert;
import org.testng.annotations.*;

/** SearchTests - 20 test cases for search functionality. */
public class SearchTests extends BaseTest {
    @BeforeMethod(alwaysRun = true, dependsOnMethods = "methodSetup") public void setup() { loginAsTestUser(); }

    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_001_marketplaceRendered() { navigateToSection("marketplace"); Assert.assertEquals(getActiveSection(),"marketplace"); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_002_listingsPresent() { navigateToSection("marketplace"); Object count = executeScript("return JSON.parse(localStorage.getItem('fc_listings')||'[]').length;"); Assert.assertTrue(((Number)count).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_003_searchByExactCrop() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop&&x.crop.toLowerCase().includes('wheat')).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_004_searchByPartialCrop() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop&&x.crop.toLowerCase().includes('whe')).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_005_searchByLocation() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.location&&x.location.toLowerCase().includes('delhi')).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_006_searchEmptyQuery() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop&&x.crop.toLowerCase().includes('')).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_007_searchNoResults() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop&&x.crop.toLowerCase().includes('zzzzzznotexist')).length;"); Assert.assertEquals(((Number)r).intValue(),0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_008_searchCaseInsensitive() { Object r1 = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop&&x.crop.toLowerCase().includes('wheat')).length;"); Object r2 = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop&&x.crop.toLowerCase().includes('WHEAT'.toLowerCase())).length;"); Assert.assertEquals(r1,r2); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_009_searchSpecialChars() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop&&x.crop.includes('@#$')).length;"); Assert.assertEquals(((Number)r).intValue(),0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_010_searchSQLInjection() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop&&x.crop.includes(\"' OR 1=1\")).length;"); Assert.assertEquals(((Number)r).intValue(),0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_011_searchBySeller() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.seller&&x.seller.toLowerCase().includes('farmer')).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_012_searchByPhone() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.phone&&x.phone.includes('987')).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_013_searchResultAccuracy() { executeScript("localStorage.setItem('fc_listings',JSON.stringify([{id:1,crop:'UniqueTestCropXYZ',qty:'1',price:1,location:'L',seller:'S',phone:'9876543210'}]));"); Object r = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).filter(x=>x.crop==='UniqueTestCropXYZ').length;"); Assert.assertEquals(((Number)r).intValue(),1); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_014_searchLongQuery() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop&&x.crop.includes('a'.repeat(100))).length;"); Assert.assertEquals(((Number)r).intValue(),0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_015_searchPreservesData() { Object before = executeScript("return JSON.parse(localStorage.getItem('fc_listings')||'[]').length;"); executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.filter(x=>true);"); Object after = executeScript("return JSON.parse(localStorage.getItem('fc_listings')||'[]').length;"); Assert.assertEquals(before,after); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_016_searchByPriceRange() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.price>=100&&x.price<=5000).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_017_commoditiesSearchable() { Object count = executeScript("return typeof COMMODITIES!=='undefined'?COMMODITIES.length:0;"); Assert.assertTrue(((Number)count).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_018_marketsSearchable() { Object count = executeScript("return typeof MARKETS!=='undefined'?MARKETS.length:0;"); Assert.assertTrue(((Number)count).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_019_searchStateReset() { navigateToSection("marketplace"); navigateToSection("dashboard"); navigateToSection("marketplace"); Assert.assertEquals(getActiveSection(),"marketplace"); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_SRCH_020_searchPerformance() { long start = System.currentTimeMillis(); executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.filter(x=>x.crop&&x.crop.includes('test'));"); long duration = System.currentTimeMillis()-start; Assert.assertTrue(duration<5000,"Search should complete within 5s"); }
}
