package com.farmconnect.automation.tests.filters;
import com.farmconnect.automation.base.BaseTest;
import com.farmconnect.automation.utils.RetryAnalyzer;
import org.testng.Assert;
import org.testng.annotations.*;

/** FilterTests - 20 test cases for filter functionality. */
public class FilterTests extends BaseTest {
    @BeforeMethod(alwaysRun = true, dependsOnMethods = "methodSetup") public void setup() { loginAsTestUser(); }

    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_001_filterByFarmerRole() { Object r = executeScript("var u=JSON.parse(localStorage.getItem('fc_users')||'[]');return u.filter(x=>x.role==='farmer').length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_002_filterByBuyerRole() { Object r = executeScript("var u=JSON.parse(localStorage.getItem('fc_users')||'[]');return u.filter(x=>x.role==='buyer').length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_003_filterByTraderRole() { Object r = executeScript("var u=JSON.parse(localStorage.getItem('fc_users')||'[]');return u.filter(x=>x.role==='trader').length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_004_filterByAdminRole() { Object r = executeScript("var u=JSON.parse(localStorage.getItem('fc_users')||'[]');return u.filter(x=>x.role==='admin').length;"); Assert.assertTrue(((Number)r).intValue()>=1); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_005_filterListingsByPrice() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.price>500).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_006_filterListingsLowPrice() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.price<=500).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_007_filterByCropType() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.crop==='Rice'||x.crop==='rice').length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_008_filterByRegion() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.location&&x.location.includes('Delhi')).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_009_filterCombinedCropAndPrice() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>(x.crop==='Wheat'||x.crop==='wheat')&&x.price>100).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_010_filterReturnsSubset() { Object all = executeScript("return JSON.parse(localStorage.getItem('fc_listings')||'[]').length;"); Object filtered = executeScript("return JSON.parse(localStorage.getItem('fc_listings')||'[]').filter(x=>x.price>99999).length;"); Assert.assertTrue(((Number)filtered).intValue()<=((Number)all).intValue()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_011_orderFilterAll() { navigateToSection("orders"); Assert.assertEquals(getActiveSection(),"orders"); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_012_orderFilterActive() { Object r = executeScript("var o=JSON.parse(localStorage.getItem('fc_orders')||'[]');return o.filter(x=>x.status==='active').length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_013_orderFilterCompleted() { Object r = executeScript("var o=JSON.parse(localStorage.getItem('fc_orders')||'[]');return o.filter(x=>x.status==='completed').length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_014_orderFilterCancelled() { Object r = executeScript("var o=JSON.parse(localStorage.getItem('fc_orders')||'[]');return o.filter(x=>x.status==='cancelled').length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_015_emptyFilterReturnsAll() { Object all = executeScript("return JSON.parse(localStorage.getItem('fc_listings')||'[]').length;"); Object filtered = executeScript("return JSON.parse(localStorage.getItem('fc_listings')||'[]').filter(()=>true).length;"); Assert.assertEquals(all,filtered); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_016_filterDoesNotMutate() { Object before = executeScript("return JSON.stringify(JSON.parse(localStorage.getItem('fc_listings')||'[]'));"); executeScript("JSON.parse(localStorage.getItem('fc_listings')||'[]').filter(x=>x.price>100);"); Object after = executeScript("return JSON.stringify(JSON.parse(localStorage.getItem('fc_listings')||'[]'));"); Assert.assertEquals(before,after); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_017_filterByQuantity() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.qty&&parseInt(x.qty)>50).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_018_chainedFilters() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.price>0).filter(x=>x.crop).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_019_filterPerformance() { long s=System.currentTimeMillis(); executeScript("for(var i=0;i<100;i++)JSON.parse(localStorage.getItem('fc_listings')||'[]').filter(x=>x.price>0);"); Assert.assertTrue(System.currentTimeMillis()-s<5000); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_FLTR_020_filterSortCombined() { Object r = executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');return l.filter(x=>x.price>0).sort((a,b)=>a.price-b.price).length;"); Assert.assertTrue(((Number)r).intValue()>=0); }
}
