package com.farmconnect.automation.tests.regression;
import com.farmconnect.automation.base.BaseTest;
import com.farmconnect.automation.data.TestData;
import com.farmconnect.automation.utils.RetryAnalyzer;
import org.testng.Assert;
import org.testng.annotations.*;

/** RegressionSuiteTests - 25 regression test cases covering critical end-to-end flows. */
public class RegressionSuiteTests extends BaseTest {
    @BeforeMethod(alwaysRun = true, dependsOnMethods = "methodSetup") public void setup() { clearAppState(); }

    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_001_fullLoginFlow() { performLogin(TestData.ADMIN_PHONE,TestData.ADMIN_PASSWORD); Assert.assertTrue(isAppDisplayed()); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_002_fullRegistrationFlow() { clickElement("#showRegister"); try{Thread.sleep(500);}catch(Exception e){} executeScript("document.getElementById('regName').value='Regression User';document.getElementById('regPhone').value='9111222333';document.getElementById('regPassword').value='regpass123';document.getElementById('regLocation').value='Regression City';document.getElementById('registerBtn').click();"); try{Thread.sleep(3000);}catch(Exception e){} Assert.assertTrue(isAppDisplayed()||isAuthScreenDisplayed()); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_003_loginNavigateLogout() { loginAsAdmin(); navigateToSection("prediction"); navigateToSection("dashboard"); executeScript("localStorage.removeItem('fc_current_user');location.reload();"); try{Thread.sleep(3000);}catch(Exception e){} Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_004_allSectionsLoad() { loginAsTestUser(); String[] s={"dashboard","prediction","market","marketplace","orders"}; for(String sec:s){navigateToSection(sec); Assert.assertEquals(getActiveSection(),sec,"Section "+sec+" should load");} }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_005_themeTogglePersistence() { loginAsTestUser(); String orig=(String)executeScript("return document.documentElement.dataset.theme;"); clickElementById("themeToggle"); String changed=(String)executeScript("return document.documentElement.dataset.theme;"); Assert.assertNotEquals(orig,changed); }
    @Test(priority = 1, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_006_languageToggleCycles() { loginAsTestUser(); for(int i=0;i<5;i++) clickElementById("langToggle"); Assert.assertTrue(isAppDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_007_invalidLoginThenValidLogin() { performLogin("9999999999","wrong"); Assert.assertTrue(isAuthScreenDisplayed()); performLogin(TestData.ADMIN_PHONE,TestData.ADMIN_PASSWORD); Assert.assertTrue(isAppDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_008_dataIntegrityAfterOperations() { loginAsTestUser(); executeScript("var l=JSON.parse(localStorage.getItem('fc_listings')||'[]');l.push({id:777,crop:'RegTest',qty:'10',price:999});localStorage.setItem('fc_listings',JSON.stringify(l));"); Object found = executeScript("return JSON.parse(localStorage.getItem('fc_listings')).find(x=>x.id===777).crop;"); Assert.assertEquals(found,"RegTest"); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_009_predictionFlowWorks() { loginAsTestUser(); navigateToSection("prediction"); Assert.assertEquals(getActiveSection(),"prediction"); clickElement("[onclick*='forecast'],[onclick*='predict'],.forecast-btn"); try{Thread.sleep(3000);}catch(Exception e){} Assert.assertTrue(isAppDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_010_marketplaceFlowWorks() { loginAsTestUser(); navigateToSection("marketplace"); Assert.assertEquals(getActiveSection(),"marketplace"); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_011_ordersFlowWorks() { loginAsTestUser(); navigateToSection("orders"); Assert.assertEquals(getActiveSection(),"orders"); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_012_weatherFlowWorks() { loginAsTestUser(); navigateToSection("weather"); Assert.assertEquals(getActiveSection(),"weather"); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_013_analyticsFlowWorks() { loginAsTestUser(); navigateToSection("analytics"); Assert.assertEquals(getActiveSection(),"analytics"); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_014_adminFullAccess() { loginAsAdmin(); String[] sections={"dashboard","prediction","market","marketplace","orders"}; for(String s:sections) navigateToSection(s); Assert.assertTrue(isAppDisplayed()); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_015_forgotPasswordFlow() { clickElement("#showForgot"); try{Thread.sleep(500);}catch(Exception e){} setInputValue("forgotPhone",TestData.ADMIN_PHONE); setInputValue("forgotNewPassword","newpass1234"); clickElementById("resetPasswordBtn"); try{Thread.sleep(2000);}catch(Exception e){} Assert.assertTrue(true); }
    @Test(priority = 2, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_016_multipleUsersSameDevice() { loginAsAdmin(); clearAppState(); loginAsTestUser(); clearAppState(); loginAsAdmin(); Assert.assertTrue(isAppDisplayed()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_017_localStorageIntegrity() { loginAsTestUser(); Object users = executeScript("try{JSON.parse(localStorage.getItem('fc_users'));return true;}catch(e){return false;}"); Assert.assertEquals(users,true); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_018_appRecoveryAfterClear() { loginAsTestUser(); executeScript("localStorage.clear();location.reload();"); try{Thread.sleep(3000);}catch(Exception e){} Assert.assertTrue(isAuthScreenDisplayed()); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_019_statCardsDataAccuracy() { loginAsTestUser(); navigateToSection("dashboard"); int cards=(int)(long)(Long)executeScript("return document.querySelectorAll('.stat-card').length;"); Assert.assertTrue(cards>=0); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_020_navbarConsistency() { loginAsTestUser(); String[] sections={"prediction","market","dashboard"}; for(String s:sections){navigateToSection(s); Assert.assertTrue(isElementVisible("#navbar"));} }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_021_authUIElements() { Assert.assertTrue(isElementVisible("#loginForm")); Assert.assertTrue(isElementVisible("#loginPhone")); Assert.assertTrue(isElementVisible("#loginPassword")); Assert.assertTrue(isElementVisible("#loginBtn")); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_022_registerUIElements() { clickElement("#showRegister"); try{Thread.sleep(500);}catch(Exception e){} Assert.assertTrue(isElementVisible("#registerForm")); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_023_brandingConsistent() { loginAsTestUser(); String brand = getElementText(".brand-text"); Assert.assertTrue(brand.contains("Farm")||brand.contains("Connect")); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_024_scrollAndNavigate() { loginAsTestUser(); executeScript("window.scrollTo(0,1000);"); navigateToSection("prediction"); Assert.assertEquals(getActiveSection(),"prediction"); }
    @Test(priority = 3, retryAnalyzer = RetryAnalyzer.class) public void TC_REGR_025_endToEndSmoke() { loginAsTestUser(); navigateToSection("prediction"); navigateToSection("market"); navigateToSection("marketplace"); navigateToSection("orders"); navigateToSection("dashboard"); Assert.assertTrue(isAppDisplayed(),"Full E2E smoke should pass"); }
}
